In [1]:
import numpy as np
import cv2
from PIL import Image
import os
from tqdm.notebook import tqdm, trange
import matplotlib.pyplot as plt
import pandas as pd
import datetime as datetime
%matplotlib inline

import torch
import torch.nn as nn
import torch.nn.functional as F
from math import ceil

from utils.preprocessing import preprocessing_flownet, preprocessing_pwc
from utils.load_models import load_flownet2, load_pwcnet, init_weights
from utils.plotting import flow2img, overlaySegment, showFlow
from utils.layers import warp, warp_Flow
from utils.encoding import labelMatrixOneHot, dice_coeff
import torch.utils.checkpoint
from models.pdd_net.pdd_student import OBELISK2d

# Select a GPU for the work
os.environ["CUDA_VISIBLE_DEVICES"] = '3'
available_gpus = [(torch.cuda.device(i),torch.cuda.get_device_name(i)) for i in range(torch.cuda.device_count())]
print(available_gpus)
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
device

[(<torch.cuda.device object at 0x7f740489ed30>, 'NVIDIA GeForce RTX 2080 Ti')]


device(type='cuda', index=0)

# Data

In [2]:
imgs = torch.load('/share/data_ultraschall/nicke_ma/data/train_frames_disp_6.pth')
segs = torch.load('/share/data_ultraschall/nicke_ma/data/train_segs_disp_6.pth')

test_imgs = torch.load('/share/data_ultraschall/nicke_ma/data/test_frames_disp_6.pth')
test_segs = torch.load('/share/data_ultraschall/nicke_ma/data/test_segs_disp_6.pth')

train_set = torch.arange(len(imgs))
test_set = torch.arange(len(test_imgs))

# Student

In [3]:
class OBELISK2d(nn.Module):
    def __init__(self, chan=16, size=(150,150)):
        super(OBELISK2d, self).__init__()
        channels = chan
        self.offsets = nn.Parameter(torch.randn(2, channels * 2, 2) * 0.05)
        self.layer0 = nn.Conv2d(1, 4, 5, stride=2, bias=False, padding=2)
        self.batch0 = nn.BatchNorm2d(4)

        self.layer1 = nn.Conv2d(channels * 8, channels * 4, 1, bias=False,
                                groups=1)
        self.batch1 = nn.BatchNorm2d(channels * 4)
        self.layer2 = nn.Conv2d(channels * 4, channels * 4, 3, bias=False,
                                padding=1)
        self.batch2 = nn.BatchNorm2d(channels * 4)
        self.layer3 = nn.Conv2d(channels * 4, channels * 1, 1)

        H = size[0]
        W = size[1]
        self.o_m = H // 4 +1
        self.o_n = W // 4 +1

        self.displace_range = 11
        self.disp_hw = 5
        self.ogrid_xy = F.affine_grid(torch.eye(2, 3).unsqueeze(0),
                                 (1, 1, self.o_m, self.o_n)).view(1, 1, -1, 2).cuda()
        self.disp_range = 0.25
        self.displacement_width = 11
        shift_xy = F.affine_grid(self.disp_range * torch.eye(2, 3).unsqueeze(0), (1, 1, self.displacement_width, self.displacement_width)).view(1, 1, -1, 2).cuda()
        grid_size = 32  # 25#30
        self.grid_xy = F.affine_grid(torch.eye(2, 3).unsqueeze(0),
                                (1, 1, grid_size, grid_size)).view(1, -1, 1,
                                                                   2).cuda()

    def forward(self, fixed_img, moving_img):
        img_in_f = F.avg_pool2d(fixed_img, 3, padding=1, stride=2)
        img_in_f = F.relu(self.batch0(self.layer0(img_in_f)))
        sampled_f = F.grid_sample(img_in_f,self.ogrid_xy + self.offsets[0, :, :].view(1, -1,1,2)).view(1, -1, self.o_m, self.o_n)
        sampled_f -= F.grid_sample(img_in_f,self.ogrid_xy + self.offsets[1, :, :].view(1, -1,1,2)).view(1, -1, self.o_m, self.o_n)

        x_1 = F.relu(self.batch1(self.layer1(sampled_f)))
        x_1 = F.relu(self.batch2(self.layer2(x_1)))
        features_fixed = self.layer3(x_1)
        
        img_in_m = F.avg_pool2d(moving_img, 3, padding=1, stride=2)
        img_in_m = F.relu(self.batch0(self.layer0(img_in_m)))
        sampled_m = F.grid_sample(img_in_m,self.ogrid_xy + self.offsets[0, :, :].view(1, -1,1,2)).view(1, -1, self.o_m, self.o_n)
        sampled_m -= F.grid_sample(img_in_m,self.ogrid_xy + self.offsets[1, :, :].view(1, -1,1,2)).view(1, -1, self.o_m, self.o_n)

        x_2 = F.relu(self.batch1(self.layer1(sampled_m)))
        x_2 = F.relu(self.batch2(self.layer2(x_2)))
        features_moving = self.layer3(x_2)

        ssd_distance = self.correlation_layer(features_moving, features_fixed)
        soft_cost,disp_xy = self.meanfield(ssd_distance, fixed_img, self.displace_range, self.o_m, self.o_n)
        
        return soft_cost, disp_xy


    def min_convolution(self, ssd_distance, displace_range, H, W):
        # Prepare operators for smooth dense displacement space
        pad1 = nn.ReplicationPad2d(5)
        avg1 = nn.AvgPool2d(5, stride=1)
        max1 = nn.MaxPool2d(3, stride=1)
        pad2 = nn.ReplicationPad2d(4)
        # approximate min convolution / displacement compatibility

        ssd_minconv = avg1(avg1(-max1(-pad1(
            ssd_distance.permute(0, 2, 3, 1).reshape(1, -1, self.displace_range,
                                                    self.displace_range)))))

        ssd_minconv = ssd_minconv.permute(0, 2, 3, 1).view(1, -1, H, W)
        min_conv_cost = avg1(avg1(pad2(ssd_minconv)))

        return min_conv_cost


    def meanfield(self, ssd_distance, img_fixed, displace_range, H, W):
        crnt_dev = ssd_distance.device

        cost = self.min_convolution(ssd_distance, displace_range, H, W)

        soft_cost = F.softmax(-10 * cost.view(displace_range ** 2, -1).t(), 1)

        disp_hw = (displace_range - 1) // 2
        disp_mesh_grid = disp_hw * F.affine_grid(torch.eye(2, 3).unsqueeze(0), (
        1, 1, displace_range, displace_range), align_corners=True)
        disp_mesh_grid /= torch.Tensor([(W - 1) * .5, (H - 1) * .5])

        disp_xy = torch.sum(
            soft_cost.view(1, H, W, -1, 1) * disp_mesh_grid.view(1, 1, 1, -1,
                                                                2).to(crnt_dev),
            3).permute(0, 3, 1, 2)

        return soft_cost, disp_xy


    def correlation_layer(self, feat_moving, feat_fixed):
        disp_hw = (self.displacement_width - 1) // 2
        feat_moving_unfold = F.unfold(feat_moving.transpose(1, 0),
                                    (self.displace_range, self.displace_range),
                                    padding=self.disp_hw)
        B, C, H, W = feat_fixed.size()

        ssd_distance = ((feat_moving_unfold - feat_fixed.view(C, 1, -1)) ** 2).sum(0).view(1, displace_range ** 2, H, W)

        return ssd_distance

# Teacher

In [5]:
flownet = load_flownet2().cuda()
flownet.eval()
pwc = load_pwcnet().cuda()
pwc.eval()

PWCDCNet(
  (conv1a): Sequential(
    (0): Conv2d(3, 16, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
    (1): LeakyReLU(negative_slope=0.1)
  )
  (conv1aa): Sequential(
    (0): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): LeakyReLU(negative_slope=0.1)
  )
  (conv1b): Sequential(
    (0): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): LeakyReLU(negative_slope=0.1)
  )
  (conv2a): Sequential(
    (0): Conv2d(16, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
    (1): LeakyReLU(negative_slope=0.1)
  )
  (conv2aa): Sequential(
    (0): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): LeakyReLU(negative_slope=0.1)
  )
  (conv2b): Sequential(
    (0): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): LeakyReLU(negative_slope=0.1)
  )
  (conv3a): Sequential(
    (0): Conv2d(32, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
    (1): LeakyReLU(negative_slope=0.1)

# Soft target training

In [10]:
disp_hw = 5
displace_range = 11
label_weights = torch.tensor([0.1,0.6, 0.3])# weights for background = 0.1, Vein = 0.6 and Artery = 0.3
epochs = 200
lr = 0.00025
grad_accum = 5

H=150;W=150

student = OBELISK2d(16)
student.apply(init_weights)
student.train().cuda()

optimizer = torch.optim.Adam(list(student.parameters()),lr=lr)
alpha=0.5

prev_eval = 0
best_epoch = 0

In [11]:
losses = []
accs = []
unwarped = []
scale=2
for epoch in trange(epochs, desc='epoch Loop', leave=False):
    student.train()
    # Cross Validation
    #train_set = torch.from_numpy(np.random.choice(np.arange(len(imgs)),size=int(len(imgs)*0.95), replace=False))

    #test_set = torch.arange(len(imgs))
    #for idx in train_set:
    #    test_set = test_set[test_set != idx]
    # Shuffle training examples
    #rnd_train_idx = torch.randperm(train_set.size(0))
    
    # shuffle data
    train_set_perm = torch.randperm(len(train_set))
    train_set = train_set[train_set_perm]
    # show all examples to model
    for i in trange(len(train_set), desc='Train Loop', leave=False):
        
        rnd_idx = train_set[i]
        tmp_loss = []
        p_fix = train_set[rnd_idx]

        # Get image and segmentation
        fixed = imgs[p_fix:p_fix+1,0,:].unsqueeze(0).float()
        moving = imgs[p_fix:p_fix+1,1,:].unsqueeze(0).float()

        fixed_seg = segs[p_fix:p_fix+1,0,:].contiguous() * 2
        moving_seg = segs[p_fix:p_fix+1,1,:].contiguous() * 2

        if len(torch.where(torch.histc(fixed_seg) != 0)[0]) == 3 and fixed_seg.max() <= 1:
            fixed_seg = fixed_seg*2
        if len(torch.where(torch.histc(moving_seg) != 0)[0]) == 3 and moving_seg.max() <= 1:
            moving_seg = moving_seg*2
        
        ########## PWC-Net
        # Here we rescale the images for the Teacher 
        # the flownet expects intputs that match Nx64. 
        teacher_fixed = F.interpolate(fixed, size=(scale*64,scale*64), mode='bicubic')
        teacher_moving = F.interpolate(moving, size=(scale*64,scale*64), mode='bicubic')

        # Generate the pwc flow estimation
        pwc_flow_in = preprocessing_pwc(teacher_fixed.detach().clone().reshape(scale*64,scale*64,1),teacher_moving.detach().clone().reshape(scale*64,scale*64,1)).cuda()
        pwc_flow = pwc(pwc_flow_in) 
        pwc_flow = F.interpolate(pwc_flow, size=(H,W),mode='bicubic')

        # warp the segmentations with pwc flow
        warped_pwc_seg = warp(moving_seg.float().unsqueeze(0).cuda(), pwc_flow.cuda()).cpu()
        
        ########## FlowNet2
        # Generate the flownet flow estimation
        #flow_in = preprocessing_flownet(teacher_fixed.detach().clone().reshape(scale*64,scale*64,1),teacher_moving.detach().clone().reshape(scale*64,scale*64,1)).cuda() * 255
        #flownet_flow = flownet(flow_in)
        #flownet_flow = F.interpolate(flownet_flow.cpu(), size=(H,W), mode='bicubic')

        # warp segmentation with flownet flow
        #warped_flownet_seg = warp(moving_seg.float().unsqueeze(0).cuda(), flownet_flow.cuda()).cpu()
        

        # Label preparation for PDD
        C1,Hf,Wf = moving_seg.size()
        label_moving_onehot = F.one_hot(moving_seg.long(),num_classes=3).permute(0,3,1,2).float()
        label_moving = F.interpolate(label_moving_onehot,size=(Hf//4 +1,Wf//4 +1),mode='bicubic')
        label_fixed = F.one_hot(fixed_seg.long(),num_classes=3).permute(0,3,1,2).float()
        label_fixed = F.interpolate(label_fixed,size=(Hf//4 +1,Wf//4 +1),mode='bicubic')
        # generate the "unfolded" version of the moving encoding that will result in the shifted versions per channel
        # according to the corresponding discrete displacement pair
        label_moving_unfold = F.unfold(label_moving,(displace_range,displace_range),padding=disp_hw).view(1,3,displace_range**2,-1)

        
        ########## PDD Forward pass
        soft_cost,disp_xy = student(fixed.cuda(), moving.cuda())

        # warp the label
        label_warped = torch.sum(soft_cost.cpu().t().unsqueeze(0)*label_moving_unfold.squeeze(0),1)
        
        
        #dense_flow_fit = F.interpolate(disp_xy,size=(H,W),mode='bicubic')
        #apply and evaluate transformation
        #identity = F.affine_grid(torch.eye(2,3).unsqueeze(0),(1,1,H,W),align_corners=False).cuda()
        #warped_student_seg = F.grid_sample(moving_seg.cuda().float().unsqueeze(1),identity+dense_flow_fit.permute(0,2,3,1),mode='nearest',align_corners=False).cpu() 
        
        pwc_onehot = labelMatrixOneHot(F.interpolate(warped_pwc_seg, size=(H//4 +1, W//4 +1), mode='bicubic').view(1,H//4 +1, W//4 +1), 3)
        #flownet_onehot = labelMatrixOneHot(F.interpolate(warped_flownet_seg, size=(H//4 +1, W//4 +1), mode='bicubic').view(1,H//4 +1, W//4 +1), 3)

        pwc_diff = torch.sum(torch.pow(label_warped.view(3,-1)-pwc_onehot.view(3,-1).detach(),2), 1) * label_weights
        #flownet_diff = torch.sum(torch.pow(label_warped.view(3,-1)-flownet_onehot.view(label_warped.shape),2), 1) * label_weights

        label_distance1 = torch.sum(torch.pow(label_fixed.reshape(3,-1)-label_warped.reshape(3,-1),2),1) * label_weights

        diffloss = 2*((disp_xy[0,:,1:,:]-disp_xy[0,:,:-1,:])**2).mean()+\
            2*((disp_xy[0,1:,:,:]-disp_xy[0,:-1,:,:])**2).mean()+\
            2*((disp_xy[0,:,:,1:]-disp_xy[0,:,:,:-1])**2).mean()
        
        
        #print(flownet_onehot.max())
        # Caclculate the label weighted teacher loss
        #teacher_loss = alpha * pwc_diff + (1-alpha)*flownet_diff
        
        # Combine the teacherloss with the label loss
        loss = 0.5 * pwc_diff.mean() + diffloss + label_distance1.mean() #+ 
        
        # propagate backwards
        loss.backward()
        tmp_loss.append([0.5 * pwc_diff.mean().item(),
                         label_distance1.mean().item(),
                         diffloss.item()])
        
        if i %grad_accum == 0:
            # every grad_accum iterations :Make an optimizer step
            optimizer.step()
            optimizer.zero_grad()
    

    losses.append(np.mean(tmp_loss, axis=0))
    
    student.eval()
    # Evaluate model:
    eval_dice = torch.zeros(len(test_set),2)
    for j in trange(len(test_set)-1, desc='Eval', leave=False):
        fixed = test_imgs[j:j+1,0,:].unsqueeze(0).float()
        moving = test_imgs[j:j+1,1,:].unsqueeze(0).float()

        fixed_seg = test_segs[j:j+1,0,:].contiguous() * 2
        moving_seg = test_segs[j:j+1,1,:].contiguous() * 2

        teacher_fixed = F.interpolate(fixed, size=(scale*64,scale*64), mode='bicubic')
        teacher_moving = F.interpolate(moving, size=(scale*64,scale*64), mode='bicubic')

        # Generate the pwc flow estimation
        pwc_flow_in = preprocessing_pwc(teacher_fixed.detach().clone().reshape(scale*64,scale*64,1),teacher_moving.detach().clone().reshape(scale*64,scale*64,1)).cuda()
        pwc_flow = pwc(pwc_flow_in) 
        pwc_flow = F.interpolate(pwc_flow, size=(H,W),mode='bicubic')

        # warp the segmentations with pwc flow
        warped_pwc_seg = warp(moving_seg.float().unsqueeze(0).cuda(), pwc_flow.cuda()).cpu()
        
        ########## FlowNet2
        # Generate the flownet flow estimation
        flow_in = preprocessing_flownet(teacher_fixed.detach().clone().reshape(scale*64,scale*64,1),teacher_moving.detach().clone().reshape(scale*64,scale*64,1)).cuda() * 255
        flownet_flow = flownet(flow_in)
        flownet_flow = F.interpolate(flownet_flow.cpu(), size=(H,W), mode='bicubic')

        # warp segmentation with flownet flow
        warped_flownet_seg = warp(moving_seg.float().unsqueeze(0).cuda(), flownet_flow.cuda()).cpu()
        
        oft_cost,disp_xy = student(fixed.cuda(), moving.cuda())
        pred_flow=F.interpolate(disp_xy,size=(150,150))
        
        identity = F.affine_grid(torch.eye(2,3).unsqueeze(0),(1,1,H,W),align_corners=False)
        warped_student_seg = F.grid_sample(moving_seg.unsqueeze(0).float(),identity+pred_flow.cpu().permute(0,2,3,1),mode='nearest',align_corners=False).cpu()
        
        d0 = dice_coeff(warped_student_seg.squeeze(), fixed_seg.squeeze() ,3)
        d1 = dice_coeff(warped_student_seg.squeeze(), warped_pwc_seg.squeeze() ,3)
        #dice = torch.sum(d0, d1, axis=0)
        dice = torch.stack([d0,d1])
        eval_dice[j] = dice.mean(axis=0)
    #print(eval_dice.mean(axis=0), eval_dice.mean(), ' Loss: ', np.mean(tmp_loss, axis=0))
    accs.append(eval_dice.mean())
    if eval_dice.mean() > prev_eval:
        prev_eval = eval_dice.mean()
        best_epoch = epoch
        torch.save(student.state_dict(), f'models/Experiment_2/fineTuneSoft/soft_trained_17-02.pth')
    if epoch > 10:
        if eval_dice.mean() == prev_eval:
            if eval_dice.mean() == accs[-2]:
                if eval_dice.mean() == accs[-3]:
                    print(f"Final Eval Score: {eval_dice.mean()}")
                    break
        

epoch Loop:   0%|          | 0/200 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

Train Loop:   0%|          | 0/1090 [00:00<?, ?it/s]

Eval:   0%|          | 0/122 [00:00<?, ?it/s]

In [15]:
eval_dice.mean()

tensor(0.7099)

# Fine tune

In [16]:
imgs1 = torch.load('/share/data_ultraschall/nicke_ma/data/frames_oneFixed_multipleMoving_dist2.pth')
segs1 = torch.load('/share/data_ultraschall/nicke_ma/data/segs_oneFixed_multipleMoving_dist2.pth')

imgs2 = torch.load('/share/data_ultraschall/nicke_ma/data/frames_oneFixed_multipleMoving.pth')
segs2 = torch.load('/share/data_ultraschall/nicke_ma/data/segs_oneFixed_multipleMoving.pth')

In [17]:
tune_imgs = torch.cat((imgs1,imgs2))
tune_segs = torch.cat((segs1,segs2))

break_point = int(len(tune_imgs)*0.9)
tune_set = torch.arange(break_point)
test_tune_set = torch.arange(break_point, len(tune_imgs))
#define a training split 
torch.manual_seed(42)
# Now, we prepare our train & test dataset.
#tune_set = torch.from_numpy(np.random.choice(np.arange(len(tune_imgs)),size=int(len(tune_imgs)*0.9), replace=False))

#test_tune_set = torch.arange(len(tune_imgs))
#for idx in tune_set:
#    test_tune_set = test_tune_set[test_tune_set != idx]


print(f"{tune_set.shape[0]} train examples")
print(f"{test_tune_set.shape[0]} test examples")

3285 train examples
366 test examples


In [19]:
obel = OBELISK2d(16)
path_to_state_dict = f'models/Experiment_2/fineTuneSoft/soft_trained_17-02.pth'
obel.load_state_dict(torch.load(path_to_state_dict))
obel.cuda()

OBELISK2d(
  (layer0): Conv2d(1, 4, kernel_size=(5, 5), stride=(2, 2), padding=(2, 2), bias=False)
  (batch0): BatchNorm2d(4, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (layer1): Conv2d(128, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
  (batch1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (layer2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
  (batch2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (layer3): Conv2d(64, 16, kernel_size=(1, 1), stride=(1, 1))
)

In [20]:
disp_hw = 5
displace_range = 11
epochs = 200
lr = 0.00025
grad_accum = 5
optimizer = torch.optim.Adam(list(obel.parameters()),lr=lr, weight_decay=0.000005)

best_epoch = 0
prev_eval = 0

In [21]:
losses = []
accs = []
unwapred = []
for epoch in trange(epochs):

    # shuffle data
    tune_set_perm = torch.randperm(len(tune_set))
    tune_set = tune_set[tune_set_perm]
    # show all examples to model
    for i in trange(len(tune_set), desc='Train loop', leave=False):
        rnd_idx = tune_set[i]
        loss_tmp = []
        p_fix = tune_set[rnd_idx]

        # Get image and segmentation
        fixed = tune_imgs[p_fix:p_fix+1,0,:].unsqueeze(0).float()
        moving = tune_imgs[p_fix:p_fix+1,1,:].unsqueeze(0).float()

        fixed_seg = tune_segs[p_fix:p_fix+1,0,:].contiguous() * 2
        moving_seg = tune_segs[p_fix:p_fix+1,1,:].contiguous() * 2

        if len(torch.where(torch.histc(fixed_seg) != 0)[0]) == 3 and fixed_seg.max() <= 1:
            fixed_seg = fixed_seg*2
        if len(torch.where(torch.histc(moving_seg) != 0)[0]) == 3 and moving_seg.max() <= 1:
            moving_seg = moving_seg*2
            
        # Downsize the label
        C1,Hf,Wf = moving_seg.size()
        label_moving = F.one_hot(moving_seg.long(),num_classes=3).permute(0,3,1,2).float()
        label_moving = F.interpolate(label_moving,size=(Hf//4 +1,Wf//4 +1),mode='bicubic')
        
        label_fixed = F.one_hot(fixed_seg.long(),num_classes=3).permute(0,3,1,2).float()
        label_fixed = F.interpolate(label_fixed,size=(Hf//4 +1,Wf//4 +1),mode='bicubic')
        # generate the "unfolded" version of the moving encoding that will result in the shifted versions per channel
        # according to the corresponding discrete displacement pair
        label_moving_unfold = F.unfold(label_moving,(displace_range,displace_range),padding=disp_hw).view(1,3,displace_range**2,-1)

        #with torch.cuda.amp.autocast():
        # passed through obelisk layer
        soft_cost,disp_xy = obel(fixed.cuda(), moving.cuda())      # fixed
        #feat50 = obel(moving.cuda())     # moving

         # compute the cost tensor using the correlation layer
        #ssd_distance = correlation_layer(displace_range, feat50, feat00)

        # compute the MIN-convolution & probabilistic output with the given function
        #soft_cost,disp_xy = meanfield(ssd_distance, fixed, displace_range, H//4 +1, W//4 +1)

        label_warped = torch.sum(soft_cost.cpu().t().unsqueeze(0)*label_moving_unfold.squeeze(0),1)
        
        #print(((torch.pow(label_fixed.reshape(3,-1)-label_warped.reshape(3,-1),2)).T.mul(label_weights)).T.shape)
        label_distance1 = torch.sum((torch.pow(label_fixed.reshape(3,-1)-label_warped.reshape(3,-1),2)),1) * label_weights
        #label_distance1 = label_distance1 * label_weights 

        diffloss = 1.5*((disp_xy[0,:,1:,:]-disp_xy[0,:,:-1,:])**2).mean()+\
            1.5*((disp_xy[0,1:,:,:]-disp_xy[0,:-1,:,:])**2).mean()+\
            1.5*((disp_xy[0,:,:,1:]-disp_xy[0,:,:,:-1])**2).mean()


        loss = label_distance1.mean() + diffloss
        # perform the backpropagation and weight updates
        loss.backward()
        loss_tmp.append(loss.item())

        if (i+1)%grad_accum == 0:
            # every grad_accum iterations :Make an optimizer step
            optimizer.step()
            optimizer.zero_grad()

    
    losses.append(np.mean(loss_tmp))
    
    # Evaluate model:
    eval_dice = torch.zeros(len(test_tune_set),2)
    for j in trange(len(test_tune_set)-1, desc='Eval', leave=False):
        fixed = imgs[j:j+1,0,:].unsqueeze(0).float()
        moving = imgs[j:j+1,1,:].unsqueeze(0).float()

        fixed_seg = segs[j:j+1,0,:].contiguous() * 2
        moving_seg = segs[j:j+1,1,:].contiguous() * 2
        
        oft_cost,disp_xy = obel(fixed.cuda(), moving.cuda())
        pred_flow=F.interpolate(disp_xy,size=(150,150))
        
        identity = F.affine_grid(torch.eye(2,3).unsqueeze(0),(1,1,H,W),align_corners=False)
        warped_student_seg = F.grid_sample(moving_seg.unsqueeze(0).float(),identity+pred_flow.cpu().permute(0,2,3,1),mode='nearest',align_corners=False).cpu()
        
        d0 = dice_coeff(warped_student_seg.squeeze(), fixed_seg ,3)
        eval_dice[j] = d0
    print(eval_dice.mean(axis=0), eval_dice.mean(), " Loss: ", np.mean(loss_tmp))
    accs.append(eval_dice.mean())
    if eval_dice.mean() > prev_eval:
        prev_eval = eval_dice.mean()
        best_epoch = epoch
        torch.save(obel.state_dict(), f'models/Experiment_2/fineTuneSoft/tuned-17-02.pth')
    if epoch > 10:
        if eval_dice.mean() == prev_eval:
            if eval_dice.mean() == accs[-2]:
                if eval_dice.mean() == accs[-3]:
                    print(f"Final Eval Score: {eval_dice.mean()}")
                    break

  0%|          | 0/200 [00:00<?, ?it/s]

Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5194, 0.8215]) tensor(0.6704)  Loss:  6.185667991638184


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5147, 0.8150]) tensor(0.6648)  Loss:  2.214578866958618


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5147, 0.8155]) tensor(0.6651)  Loss:  1.512544870376587


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5124, 0.8172]) tensor(0.6648)  Loss:  12.093459129333496


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5139, 0.8197]) tensor(0.6668)  Loss:  4.263706684112549


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5115, 0.8161]) tensor(0.6638)  Loss:  26.690994262695312


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5113, 0.8147]) tensor(0.6630)  Loss:  0.9519388675689697


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5135, 0.8188]) tensor(0.6661)  Loss:  20.069011688232422


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5135, 0.8185]) tensor(0.6660)  Loss:  2.0531857013702393


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5155, 0.8200]) tensor(0.6677)  Loss:  12.327791213989258


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5112, 0.8155]) tensor(0.6633)  Loss:  4.530788898468018


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5146, 0.8183]) tensor(0.6664)  Loss:  1.8921456336975098


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5161, 0.8195]) tensor(0.6678)  Loss:  3.0010106563568115


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5164, 0.8195]) tensor(0.6680)  Loss:  1.4845657348632812


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5141, 0.8178]) tensor(0.6659)  Loss:  5.336339473724365


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5147, 0.8194]) tensor(0.6671)  Loss:  3.163433790206909


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5160, 0.8206]) tensor(0.6683)  Loss:  10.030444145202637


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5121, 0.8144]) tensor(0.6633)  Loss:  1.737551212310791


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5156, 0.8181]) tensor(0.6669)  Loss:  14.199036598205566


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5122, 0.8154]) tensor(0.6638)  Loss:  3.2145543098449707


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5136, 0.8170]) tensor(0.6653)  Loss:  4.294142246246338


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5137, 0.8207]) tensor(0.6672)  Loss:  5.460716247558594


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5111, 0.8198]) tensor(0.6654)  Loss:  2.794431686401367


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5156, 0.8191]) tensor(0.6673)  Loss:  6.0981292724609375


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5131, 0.8174]) tensor(0.6653)  Loss:  5.818952560424805


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5135, 0.8187]) tensor(0.6661)  Loss:  11.811090469360352


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5127, 0.8179]) tensor(0.6653)  Loss:  2.5837488174438477


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5127, 0.8187]) tensor(0.6657)  Loss:  4.972474575042725


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5137, 0.8171]) tensor(0.6654)  Loss:  3.4128661155700684


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5154, 0.8184]) tensor(0.6669)  Loss:  7.040471076965332


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5133, 0.8193]) tensor(0.6663)  Loss:  13.257611274719238


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5118, 0.8171]) tensor(0.6644)  Loss:  17.887693405151367


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5120, 0.8160]) tensor(0.6640)  Loss:  1.785775899887085


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5108, 0.8163]) tensor(0.6636)  Loss:  2.6526198387145996


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5128, 0.8175]) tensor(0.6651)  Loss:  3.2276196479797363


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5141, 0.8181]) tensor(0.6661)  Loss:  3.111931562423706


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5132, 0.8172]) tensor(0.6652)  Loss:  3.220597505569458


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5135, 0.8184]) tensor(0.6660)  Loss:  2.4186010360717773


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5126, 0.8181]) tensor(0.6653)  Loss:  2.0923378467559814


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5144, 0.8173]) tensor(0.6658)  Loss:  0.9838930368423462


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5119, 0.8178]) tensor(0.6648)  Loss:  1.407265067100525


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5128, 0.8172]) tensor(0.6650)  Loss:  21.89266586303711


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5120, 0.8158]) tensor(0.6639)  Loss:  4.211350917816162


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5145, 0.8191]) tensor(0.6668)  Loss:  1.7132850885391235


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5126, 0.8172]) tensor(0.6649)  Loss:  2.959761619567871


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5139, 0.8181]) tensor(0.6660)  Loss:  1.4129512310028076


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5129, 0.8171]) tensor(0.6650)  Loss:  2.350494861602783


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5145, 0.8178]) tensor(0.6661)  Loss:  1.6589988470077515


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5129, 0.8178]) tensor(0.6653)  Loss:  2.5950348377227783


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5140, 0.8180]) tensor(0.6660)  Loss:  20.14140510559082


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5117, 0.8168]) tensor(0.6642)  Loss:  1.372901439666748


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5138, 0.8173]) tensor(0.6656)  Loss:  2.2808871269226074


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5117, 0.8181]) tensor(0.6649)  Loss:  3.283294916152954


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5140, 0.8183]) tensor(0.6661)  Loss:  2.8770153522491455


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5132, 0.8180]) tensor(0.6656)  Loss:  12.428465843200684


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5141, 0.8185]) tensor(0.6663)  Loss:  4.793361663818359


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5127, 0.8170]) tensor(0.6649)  Loss:  2.6297991275787354


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5137, 0.8163]) tensor(0.6650)  Loss:  17.85749626159668


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5143, 0.8175]) tensor(0.6659)  Loss:  2.7866978645324707


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5136, 0.8174]) tensor(0.6655)  Loss:  4.885572910308838


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5138, 0.8181]) tensor(0.6659)  Loss:  6.70027494430542


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5123, 0.8166]) tensor(0.6645)  Loss:  23.994571685791016


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5128, 0.8175]) tensor(0.6652)  Loss:  1.5452368259429932


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5141, 0.8168]) tensor(0.6654)  Loss:  2.3654258251190186


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5130, 0.8171]) tensor(0.6651)  Loss:  9.224529266357422


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5146, 0.8187]) tensor(0.6666)  Loss:  3.855503797531128


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5133, 0.8167]) tensor(0.6650)  Loss:  11.327622413635254


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5134, 0.8172]) tensor(0.6653)  Loss:  9.666154861450195


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5133, 0.8166]) tensor(0.6650)  Loss:  16.978302001953125


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5129, 0.8167]) tensor(0.6648)  Loss:  1.873889684677124


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5127, 0.8167]) tensor(0.6647)  Loss:  1.3748966455459595


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5142, 0.8156]) tensor(0.6649)  Loss:  13.664124488830566


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5135, 0.8182]) tensor(0.6659)  Loss:  3.0572826862335205


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5132, 0.8169]) tensor(0.6650)  Loss:  3.001382827758789


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5118, 0.8157]) tensor(0.6637)  Loss:  2.218961000442505


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5116, 0.8161]) tensor(0.6639)  Loss:  5.1585540771484375


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5136, 0.8174]) tensor(0.6655)  Loss:  2.8602983951568604


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5137, 0.8165]) tensor(0.6651)  Loss:  3.0027835369110107


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5146, 0.8151]) tensor(0.6649)  Loss:  5.151967525482178


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5132, 0.8162]) tensor(0.6647)  Loss:  2.366137742996216


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5146, 0.8180]) tensor(0.6663)  Loss:  2.374485492706299


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5130, 0.8145]) tensor(0.6637)  Loss:  1.1950103044509888


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5116, 0.8162]) tensor(0.6639)  Loss:  25.321378707885742


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5135, 0.8154]) tensor(0.6645)  Loss:  2.355255365371704


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5130, 0.8147]) tensor(0.6639)  Loss:  10.089590072631836


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5140, 0.8157]) tensor(0.6649)  Loss:  3.8264644145965576


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5143, 0.8145]) tensor(0.6644)  Loss:  3.3975203037261963


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5119, 0.8151]) tensor(0.6635)  Loss:  1.745705485343933


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5142, 0.8142]) tensor(0.6642)  Loss:  0.8953807950019836


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5126, 0.8155]) tensor(0.6640)  Loss:  2.2016477584838867


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5127, 0.8157]) tensor(0.6642)  Loss:  4.084557056427002


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5115, 0.8128]) tensor(0.6622)  Loss:  7.4710516929626465


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5125, 0.8149]) tensor(0.6637)  Loss:  0.9737843871116638


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5142, 0.8161]) tensor(0.6652)  Loss:  25.49463653564453


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5139, 0.8147]) tensor(0.6643)  Loss:  0.3697514533996582


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5138, 0.8145]) tensor(0.6642)  Loss:  4.742918491363525


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5142, 0.8149]) tensor(0.6645)  Loss:  1.481132984161377


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5126, 0.8159]) tensor(0.6643)  Loss:  12.840758323669434


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5126, 0.8146]) tensor(0.6636)  Loss:  32.5742073059082


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5136, 0.8147]) tensor(0.6641)  Loss:  1.1491107940673828


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5128, 0.8146]) tensor(0.6637)  Loss:  1.2528412342071533


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5127, 0.8137]) tensor(0.6632)  Loss:  2.188676595687866


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5142, 0.8159]) tensor(0.6650)  Loss:  4.764377593994141


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5125, 0.8140]) tensor(0.6633)  Loss:  7.476616382598877


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5124, 0.8141]) tensor(0.6632)  Loss:  1.8183059692382812


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5130, 0.8142]) tensor(0.6636)  Loss:  13.970314979553223


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5130, 0.8141]) tensor(0.6635)  Loss:  1.455590009689331


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5121, 0.8132]) tensor(0.6626)  Loss:  2.6935977935791016


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5144, 0.8146]) tensor(0.6645)  Loss:  19.098695755004883


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5124, 0.8143]) tensor(0.6634)  Loss:  2.9578092098236084


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5132, 0.8131]) tensor(0.6631)  Loss:  18.71091079711914


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5136, 0.8141]) tensor(0.6639)  Loss:  7.129708290100098


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5125, 0.8136]) tensor(0.6630)  Loss:  3.0387749671936035


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5140, 0.8133]) tensor(0.6637)  Loss:  6.336249828338623


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5125, 0.8137]) tensor(0.6631)  Loss:  6.066566467285156


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5132, 0.8132]) tensor(0.6632)  Loss:  2.6169986724853516


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5122, 0.8133]) tensor(0.6628)  Loss:  2.244823694229126


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5118, 0.8128]) tensor(0.6623)  Loss:  6.7896270751953125


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5127, 0.8130]) tensor(0.6629)  Loss:  4.315937042236328


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5140, 0.8127]) tensor(0.6634)  Loss:  16.195756912231445


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5130, 0.8127]) tensor(0.6628)  Loss:  2.121689796447754


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5135, 0.8128]) tensor(0.6632)  Loss:  18.98710823059082


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5126, 0.8121]) tensor(0.6623)  Loss:  1.286612868309021


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5130, 0.8133]) tensor(0.6632)  Loss:  5.671626091003418


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5115, 0.8134]) tensor(0.6625)  Loss:  9.88768482208252


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5137, 0.8119]) tensor(0.6628)  Loss:  1.9941120147705078


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5119, 0.8126]) tensor(0.6622)  Loss:  12.577239036560059


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5123, 0.8112]) tensor(0.6618)  Loss:  1.1115831136703491


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5129, 0.8127]) tensor(0.6628)  Loss:  2.911071538925171


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5116, 0.8123]) tensor(0.6619)  Loss:  1.9325203895568848


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5134, 0.8123]) tensor(0.6629)  Loss:  11.272719383239746


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5135, 0.8132]) tensor(0.6633)  Loss:  14.430953979492188


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5131, 0.8114]) tensor(0.6622)  Loss:  5.203036308288574


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5100, 0.8117]) tensor(0.6609)  Loss:  1.2140840291976929


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5112, 0.8121]) tensor(0.6617)  Loss:  2.7770938873291016


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5123, 0.8117]) tensor(0.6620)  Loss:  1.9262853860855103


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5122, 0.8115]) tensor(0.6618)  Loss:  4.1499762535095215


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5130, 0.8110]) tensor(0.6620)  Loss:  6.082664966583252


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5120, 0.8129]) tensor(0.6625)  Loss:  6.0058064460754395


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5112, 0.8123]) tensor(0.6618)  Loss:  0.15851223468780518


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5132, 0.8125]) tensor(0.6628)  Loss:  1.5859743356704712


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5111, 0.8110]) tensor(0.6610)  Loss:  0.7719412446022034


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5116, 0.8103]) tensor(0.6610)  Loss:  3.0744991302490234


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5116, 0.8109]) tensor(0.6613)  Loss:  3.5287904739379883


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5117, 0.8111]) tensor(0.6614)  Loss:  4.746373176574707


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5124, 0.8125]) tensor(0.6625)  Loss:  0.9653028249740601


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5135, 0.8121]) tensor(0.6628)  Loss:  1.0332303047180176


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5116, 0.8121]) tensor(0.6618)  Loss:  4.907127857208252


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5124, 0.8117]) tensor(0.6620)  Loss:  1.0798224210739136


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5129, 0.8115]) tensor(0.6622)  Loss:  3.1712841987609863


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5112, 0.8110]) tensor(0.6611)  Loss:  3.447808265686035


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5130, 0.8108]) tensor(0.6619)  Loss:  0.6876091361045837


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5125, 0.8113]) tensor(0.6619)  Loss:  12.217116355895996


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5124, 0.8107]) tensor(0.6615)  Loss:  3.518778085708618


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5116, 0.8108]) tensor(0.6612)  Loss:  1.3358871936798096


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5112, 0.8106]) tensor(0.6609)  Loss:  2.1880857944488525


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5131, 0.8093]) tensor(0.6612)  Loss:  8.282522201538086


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5126, 0.8104]) tensor(0.6615)  Loss:  7.600351810455322


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5121, 0.8097]) tensor(0.6609)  Loss:  2.88824725151062


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5108, 0.8106]) tensor(0.6607)  Loss:  13.661149024963379


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5128, 0.8106]) tensor(0.6617)  Loss:  9.075026512145996


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5121, 0.8103]) tensor(0.6612)  Loss:  0.9408483505249023


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5131, 0.8108]) tensor(0.6620)  Loss:  4.123414516448975


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5113, 0.8090]) tensor(0.6601)  Loss:  4.454533100128174


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5111, 0.8091]) tensor(0.6601)  Loss:  6.1078314781188965


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5109, 0.8104]) tensor(0.6606)  Loss:  5.67083740234375


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5127, 0.8098]) tensor(0.6612)  Loss:  5.955883502960205


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5105, 0.8104]) tensor(0.6604)  Loss:  3.073568344116211


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5109, 0.8104]) tensor(0.6606)  Loss:  1.432772159576416


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5114, 0.8103]) tensor(0.6608)  Loss:  1.2205917835235596


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5112, 0.8098]) tensor(0.6605)  Loss:  14.927013397216797


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5113, 0.8100]) tensor(0.6607)  Loss:  0.6337218880653381


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5120, 0.8108]) tensor(0.6614)  Loss:  0.524465799331665


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5114, 0.8115]) tensor(0.6614)  Loss:  4.163363933563232


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5110, 0.8110]) tensor(0.6610)  Loss:  1.8249263763427734


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5109, 0.8099]) tensor(0.6604)  Loss:  2.1399405002593994


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5133, 0.8110]) tensor(0.6621)  Loss:  21.8040828704834


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5108, 0.8098]) tensor(0.6603)  Loss:  37.111244201660156


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5132, 0.8096]) tensor(0.6614)  Loss:  8.32535457611084


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5102, 0.8095]) tensor(0.6598)  Loss:  6.369457244873047


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5133, 0.8109]) tensor(0.6621)  Loss:  1.1756781339645386


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5112, 0.8089]) tensor(0.6600)  Loss:  0.46686527132987976


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5115, 0.8085]) tensor(0.6600)  Loss:  2.0427558422088623


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5104, 0.8092]) tensor(0.6598)  Loss:  2.2651195526123047


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5121, 0.8096]) tensor(0.6609)  Loss:  11.925126075744629


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5128, 0.8100]) tensor(0.6614)  Loss:  1.1372060775756836


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5126, 0.8093]) tensor(0.6610)  Loss:  13.978940963745117


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5107, 0.8098]) tensor(0.6603)  Loss:  2.016784191131592


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5112, 0.8082]) tensor(0.6597)  Loss:  26.631357192993164


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5105, 0.8095]) tensor(0.6600)  Loss:  3.6216812133789062


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5088, 0.8096]) tensor(0.6592)  Loss:  2.5317423343658447


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5121, 0.8103]) tensor(0.6612)  Loss:  3.1555347442626953


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5118, 0.8094]) tensor(0.6606)  Loss:  7.7135748863220215


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5102, 0.8096]) tensor(0.6599)  Loss:  22.506826400756836


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5104, 0.8104]) tensor(0.6604)  Loss:  3.1585617065429688


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5118, 0.8110]) tensor(0.6614)  Loss:  0.5414094924926758


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5102, 0.8090]) tensor(0.6596)  Loss:  2.4862568378448486


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5107, 0.8094]) tensor(0.6601)  Loss:  6.243492126464844


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5121, 0.8106]) tensor(0.6614)  Loss:  4.288717269897461


Train loop:   0%|          | 0/3285 [00:00<?, ?it/s]

Eval:   0%|          | 0/365 [00:00<?, ?it/s]

tensor([0.5118, 0.8090]) tensor(0.6604)  Loss:  1.8935626745224


In [22]:
import IPython
IPython.Application.instance().kernel.do_shutdown(True)

{'status': 'ok', 'restart': True}